newprogram/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from newsapp.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('newsapp.urls')),
    url(r'^$',home),

]

newsapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'newsapp'
urlpatterns = [
    url(r'^$' , views.list),
    url(r'^list/$', views.list),
    url(r'^(?P<article_id>\d+)/show/$', views.show, name='show'),
    url(r'^(?P<article_id>\d+)/comment/$', views.comment, name='comment'),

]

newsapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Article(models.Model):
    author = models.CharField(max_length=80)
    title = models.CharField(max_length=200, default='First Title')
    body = models.TextField(max_length=500)
    pub_date = models.DateTimeField('تاريخ النشر',auto_now_add=True)
    is_reviewed= models.BooleanField(verbose_name="هل تمت المراجعة؟",default=False)

#to make it in arabic user friendly
    class Meta:
        verbose_name='مقالة'
        verbose_name_plural='مقالات'

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article)
    author = models.CharField(max_length=80)
    text = models.TextField(max_length=250)
    pub_date = models.DateTimeField(auto_now_add=True)

newsapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse,HttpResponseRedirect

from django.http import Http404

#from django.http import Reverse


from.models import Article, Comment

# Create your views here.

def home(request):
    return HttpResponse('This is the homepage')

def index(request):
    return HttpResponse('Hello from the news app index view!')

def list(request):
    list = Article.objects.order_by('-pub_date')[:5]
    context = {'list':list}
    return render(request,'newsapp/list.html', context )

    #Article.objects.create(title=tex, pub_date=pub_date)
    #redirect_url = reverse('newsapp:show', args=[article_id])
    #return render(request, 'newsapp/list.html', {'article': article} )
    #return HttpResponseRedirect(redirect_url)


def show(request, article_id):
    # try:
    #     article = Article.objects.get(pk= article_id)
    # except Article.DoesNotExist:
    #     raise Http404('Sorry, this page does not exist.')
    # return render(request, 'newsapp/show.html', {'article':article} )

    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'newsapp/show.html', {'article': article})

def comment(request, article_id):
    text = request.POST['text']
    author = request.POST['author']
    article = get_object_or_404(Article, pk=article_id)

    Comment.objects.create(text=text, author=author, article=article)
    redirect_url = reverse('newsapp:show', args=[article_id])
    return HttpResponseRedirect(redirect_url)

newsapp/templates/newsapp/list.html
<!DOCTYPE html> {% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>News App </title>

    <!— Bootstrap core CSS —>
    <link href={% static "vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">

    <!— Custom styles for this template —>
    <link href={% static "css/blog-home.css" %} rel="stylesheet">

  </head>

  <body>

  <h1 class="my-4">Welcome to Incredible News
          </h1>

    <!— Navigation —>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
        <a class="navbar-brand" >Latest News</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
              <li>
                <a name=title href="{% url 'article:show' article.id %}">
                article.title</a>
              </li>



              <li>
                <a href="{% url 'article:show' article.id %}">
                Hajj Breaks Begins</a>
              </li>


        </ul>
        </div>
        </div>
    </nav>

    <!— Page Content —>
    <div class="container">

      <div class="row">

        <!— Blog Entries Column —>
        <div class="col-md-8">



        <!— Sidebar Widgets Column —>
        <div class="col-md-4">

          <!— Search Widget —>
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>




    <!— Bootstrap core JavaScript —>
    <script src={% static "vendor/jquery/jquery.min.js"%}></script>
    <script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js"}></script>

  </body>

</html>

newsapp/templates/newsapp/show.html
<!DOCTYPE html>{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ article.title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{ article.title }}</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="#">{{ article.author }}</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on {{ article.pub_date }}</p>

          <hr>

          {% if article.image %}
          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{ article.image.url }}" alt="">
          {% endif %}

          <hr>

          <!-- Post Content -->
          <p>{{ article.body }}</p>
          <hr>

          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'newsapp:comment' article.pk %}">
                <div class="form-group">
                  <input type="text" class="form-control" name="author">
                </div>
                <div class="form-group">
                  <textarea name="text" class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

          <!-- Single Comment -->
          {% for comment in article.comment_set.all %}
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ comment.author }}</h5>
              {{ comment.text }}
            </div>
          </div>
          {% endfor %}

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>